plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '2.7.18'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.Lewis'
version = '0.0.1-SNAPSHOT'
description = 'SpringStory'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// === Spring Boot 核心與 Web ===
	implementation 'org.springframework.boot:spring-boot-starter-web'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'

	// === 資料庫 (JPA & PostgreSQL) ===
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'org.postgresql:postgresql'
	// runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'

	// === API 文件 (Swagger / OpenAPI) ===
	implementation 'org.springdoc:springdoc-openapi-ui:1.7.0'
	implementation 'io.springfox:springfox-swagger2:2.9.2'

	// === Lombok 設定 ===
	compileOnly 'org.projectlombok:lombok:1.18.36'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'

	// === 測試相關 ===
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

tasks.named('test') {
	useJUnitPlatform()
}
