# Postgre ===============================================================
pgre.jpa.properties.hibernate.hbm2ddl.auto=update
pgre.datasource.driver-class-name=org.postgresql.Driver
pgre.datasource.url=jdbc:postgresql://192.168.1.66:5432/appdb
pgre.datasource.username=${pgreDB_user}
pgre.datasource.password=${pgreDB_pass}

postgre.dialect=org.hibernate.dialect.PostgreSQLDialect

#=========================================================================