name: QNAP springstory CI/CD

on:
  push:
    branches:
      - sourceconfig

jobs:
  build-and-deploy:
    runs-on: qnap-spring-env

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 3. Generate missing gradle wrapper files
        run: gradle wrapper --gradle-version 7.6

      - name: 4. Build with Gradle
        run: ./gradlew bootJar -x test

      - name: 5. Build Image and Run Container
        run: |
          docker build -t springstory:latest .
          docker stop springstory || true
          docker rm springstory || true
          docker run -d \
            --name springstory \
            --restart unless-stopped \
            --network app-1_default \
            -p 8082:8080 \
            springstory:latest
