name: QNAP springstory CI/CD

on:
  push:
    branches:
      - sourceconfig

jobs:
  build-and-deploy:
    runs-on: qnap-spring-env

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Build Image and Run Container
        run: |
          docker build -f Dockerfile -t springstory:latest .
          docker stop springstory || true
          docker rm springstory || true
          docker run -d \
            --name springstory \
            --restart unless-stopped \
            -p 8082:8080 \
            -e pgreDB_user="${{ secrets.pgreDB_user }}" \
            -e pgreDB_pass="${{ secrets.pgreDB_pass }}" \
            springstory:latest